#include <conio.h>       //header untuk fungsi clrscr & getch
#include <iostream.h>    //header untuk fungsi cout
#include <stdio.h>       //header untuk fungsi printf
int main()               //program bagian utama bisa void main

{
	clrscr();
	printf ("HELLO WORLD.\n"); //n berguna untuk pindah baris
   cout << "HELLO" ;
   cout << "\n hallo...selamat datang..."; //n disamping maka kursor ada disamping
   getch();
   return 0;
}